### PR TITLE
Pixie Dust UI Bar

### PR DESCRIPTION
**Pull request by Lbaniassad**
## Description
- DustTotalUI.cs modified, uses MainManager.Instance.FairyDust for persistence
- GardenManager.cs modified to use new DustTotalUI.cs functionality 
- PixieDustCanvas UI canvas object added
    Children: 
    - BarBackground: Image UI game object that is the background of the Pixie dust bar 
    - BarFill: ImageUI game object that increases in width proportional to the amount of Pixie Dust you have
    - PixieDustText: TextMeshPro label for the UI bar
    - DustQuanitity: the amount of pixie dust displayed numerically on the right side of the bar

Please copy over the entire PixieDustCanvasUI object and all of its children into the Main scene. The position should be at the top right of the screen, and all the positions should be configured already. 

## Motivation and Context
- Pixie dust UI bar persists through all scenes
- Pixie dust and garden connection configured 

## How Has This Been Tested?
I tried to test it by winning the gardening class, but the garden win screen won't come up. That is a separate bug that needs to be solved. So technically no tests!

### CODE REVIEW

**Review by sakshikakkad — APPROVED** [review]
there was a conflict but I think i fixed it

I'll try to fix the garden crop stuff and test the pixie dust!

**Review by sakshikakkad — CHANGES_REQUESTED** [review]
not sure what the error in garden manager is for (set points?)

**Comment by Lbaniassad** [comment]
Ok it should work ok now! Here are extra changes that I made: 
1. Pixie dust UI bar canvas scale mode: The canvas scale mode should be set to "scale with screen size" and the screen size should be 1920 x 1080
2. Fairy Character: I set the Forward Speed, Turn Speed, and Fly speed to 30, 20, and 15 respectively. i think these speeds make it easier to complete the gardening in time. The speeds need to be changed for the fairy character in all of the scenes. 
3. Garden Manager: I tried debugging the start method. I added a bunch of debug logs, which can be used to check if the cropList matches the directions at the start of the class. Now the lists match most of the time, but some of the time the directions will not include the last element in the list. Not sure why this happens.

**Comment by Lbaniassad** [comment]
Oh ONE MORE THING: 
Parsnip tree: I am not sure if it is in my scene or not (i think it is) but the tree with the purple spheres in it is kind of tall for the character to fly up and catch a fruit in time. I just scaled the Y of the tree to be 20, and since the crops are its children I scaled the crop Y to be 0.54 ( 0.27 x 2). This way the spheres are the same size as the ones on the ground but the tree is lower to the ground. If you want to do it a diff way you can! I think doing it to just one tree is ok for the alpha.

**Review by sakshikakkad — APPROVED** [review]

**Pull request merged**
